---
version: "2"
services:
    notebook:
        build: .
        ports:
            - "127.0.0.1:8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/work/notebooks
            - ./static:/home/jovyan/work/static
    r_api:
        build: .
        command: >
            jupyter kernelgateway 
            --KernelGatewayApp.api=notebook-http
            --KernelGatewayApp.ip=0.0.0.0
            --KernelGatewayApp.seed_uri='/home/jovyan/work/notebooks/scotch_api_r.ipynb'
        ports:
            - "127.0.0.1:9000:8888"
        volumes:
            - ./notebooks:/home/jovyan/work/notebooks
    python_api:
        build: .
        command: >
            jupyter kernelgateway 
            --KernelGatewayApp.api=notebook-http
            --KernelGatewayApp.ip=0.0.0.0
            --KernelGatewayApp.seed_uri='/home/jovyan/work/notebooks/scotch_api_python.ipynb'
            --NotebookHTTPPersonality.static_path='/home/jovyan/work/static'
        ports:
            - "127.0.0.1:9001:8888"
        volumes:
            - ./notebooks:/home/jovyan/work/notebooks
            - ./static:/home/jovyan/work/static
    julia_api:
        build: .
        command: >
            jupyter kernelgateway 
            --KernelGatewayApp.api=notebook-http
            --KernelGatewayApp.ip=0.0.0.0
            --KernelGatewayApp.seed_uri='/home/jovyan/work/notebooks/scotch_api_julia.ipynb'
        ports:
            - "127.0.0.1:9002:8888"
        volumes:
            - ./notebooks:/home/jovyan/work/notebooks
